mysite/mysite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name ='common'
urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='common/login.html'),name='login'),
    path('login/',auth_views.LoginView.as_view(),name='logout'),
    path('signup/', views.signup, name='signup'),
]

mysite/mysite/config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('monitor/',include('monitor.urls')),
    path('common/',include('common.urls')),
    #path('board/', include('board.urls')),
    path('admin/', admin.site.urls)
]

mysite/mysite/monitor/urls.py
from django.urls import path

from . import views


app_name='monitor'

urlpatterns = [
    # /monitor
    path('', views.index, name='index'),

    # /monitor/detail/data_id
    path('detail/<int:data_id>', views.detail, name='detail'),

    # /monitor/update
    #path('update/<int:data_id>', views.update, name='update'),

    # /monitor/delete
    #path('delete/<int:data_id>', views.delete, name='delete'),

]

mysite/mysite/common/models.py
from django.db import models

# Create your models here.

mysite/mysite/monitor/models.py
from django.db import models


class SystemEvents(models.Model):
    CustomerID = models.CharField(max_length=1000, null=True)
    ReceivedAt = models.DateTimeField('ReceivedAt', null=True)
    DeviceReportedTime = models.DateTimeField('DeviceReportedTime', null=True)
    Facility = models.IntegerField(default=0, null=True)
    Priority = models.IntegerField(default=0, null=True)
    FromHost = models.CharField(max_length=1000, null=True)
    Message = models.CharField(max_length=1000, null=True)
    NTSeverity = models.IntegerField(default=0, null=True)
    Importance = models.IntegerField(default=0, null=True)
    EventSource = models.CharField(max_length=1000, null=True)
    EventUser = models.CharField(max_length=1000, null=True)
    EventCategory = models.IntegerField(default=0, null=True)
    EventID = models.IntegerField(default=0, null=True)
    EventBinaryData = models.CharField(max_length=1000, null=True)
    MaxAvailable = models.IntegerField(default=0, null=True)
    CurrUsage = models.IntegerField(default=0, null=True)
    MinUsage = models.IntegerField(default=0, null=True)
    MaxUsage = models.IntegerField(default=0, null=True)
    InfoUnitID = models.IntegerField(default=0, null=True)
    SysLogTag = models.CharField(max_length=1000, null=True)
    EventLogType = models.CharField(max_length=1000, null=True)
    GenericFileName = models.CharField(max_length=1000, null=True)
    SystemID = models.IntegerField(default=0, null=True)

    class Meta:
        db_table ='SystemEvents'


class SystemEventsProperties(models.Model):
    question = models.ForeignKey(SystemEvents, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    class Meta:
        db_table ='SystemEventsProperties'

mysite/mysite/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email= forms.EmailField(label='이메일')

    class Meta:
        model=User
        fields=("username","email")

mysite/mysite/common/views.py
from django.shortcuts import render,redirect
from common.forms import UserForm
from django.contrib.auth import authenticate, login
# Create your views here.

def signup(request):
    if request.method == "POST":
        print("로그인 시도")
        form =UserForm(request.POST)
        if form.is_valid():
            print("값 검증 ")
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username,password=password)
            login(request,user)
            return redirect('/monitor')
    else :
        form = UserForm()

    return render(request,'common/signup.html',{'form':form})

mysite/mysite/monitor/views.py
from django.shortcuts import render
from .models import *
from django.contrib.auth.decorators import login_required


# Create your views here.
from django.http import HttpResponse

@login_required(login_url='common:login')
def index(request):
    rsyslogs = SystemEvents.objects.order_by('-id')[:10]
    context = {"rsyslogs":rsyslogs}
    return render(request, 'monitor/index.html',context)

@login_required(login_url='common:login')
def detail(request,data_id):
    rsyslogs = SystemEvents.objects.get(id=data_id)
    context = {"rsyslogs":rsyslogs}
    return render(request, 'monitor/detail.html',context)

mysite/mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>test</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">all weather</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'monitor:index'%}">Home</a></li>
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">관리 <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">test1</a></li>
          <li><a href="#">test2</a></li>
          <li><a href="#">test3</a></li>
        </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'common:signup'%}"><span class="glyphicon glyphicon-user"></span>회원가입</a></li>
      {% if user.is_authenticated %}
      <li><a href="{% url 'common:logout'%}"><span class="glyphicon glyphicon-log-out"></span>로그아웃</a></li>
      {% else %}
      <li><a href="{% url 'common:login'%}"><span class="glyphicon glyphicon-log-in"></span>로그인</a></li>
      {% endif%}
  </div>
</nav>
{%block content%}
{%endblock%}

mysite/mysite/templates/common/login.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>회원가입페이지</title>
</head>
<body>

{% block content %}
<div class="container">
  <h2>로그인</h2>
  <p></p>
<form method="post" action="{% url 'common:login'%}">
  {% csrf_token %}
  <div class="form-group">
    <label for="username">아이디</label>
    <input type="text" class="form-control" id="username"name="username">
  </div>
  <div class="form-group">
    <label for="password">비밀번호</label>
    <input type="password" class="form-control" id="password" name="password">
  </div>
  <button type="submit" class="btn btn-default">로그인</button>
</form>
{%endblock%}
</body>
</html>

mysite/mysite/templates/common/signup.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>회원가입페이지</title>
</head>
<body>
{% block content %}
<div class="container">
  <h2>회원가입</h2>

  <form method="post" action="{% url 'common:signup'%}">
<!--
  <form method="post" class="post-form">
  -->
    {% csrf_token %}
    {% include "form_errors.html" %}
    <div class="form-group">
      <label for="username">아이디</label>
      <input type="text" class="form-control" id="username" placeholder="아이디 입력" name="username" value="{{form.username.value|default_if_none:''}}">
    </div>
    <div class="form-group">
      <label for="password1">비밀번호</label>
      <input type="password" class="form-control" id="password1" placeholder="암호 입력" name="password1" value="{{form.password1.value|default_if_none:''}}">
    </div>
    <div class="form-group">
      <label for="password2">비밀번호 확인</label>
      <input type="password" class="form-control" id="password2" placeholder="암호 확인" name="password2" value="{{form.password2.value|default_if_none:''}}">
    </div>
    <div class="form-group">
      <label for="email">이메일</label>
      <input type="email" class="form-control" id="email" placeholder="이메일 입력" name="email" value="{{form.email.value|default_if_none:''}}">
    </div>
    <button type="submit" class="btn btn-default">회원가입</button>
  </form>
</div>
{%endblock%}
</body>
</html>

mysite/mysite/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong> {{field.label}} </strong>
                {{error}}
            </div>
        {%endfor%}
    {% endfor%}

    {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong> {{error}} </strong>
            </div>
    {% endfor %}
{%endif%}

mysite/mysite/templates/monitor/detail.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{%block content%}
<div class="container">
  <h2>로그관리상세보기</h2>
  <p>#Rsyslog, #모니터링</p>
  {{rsyslogs.id}}
  <div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>번호</th>
        <th>필드</th>
        <th>값</th>
      </tr>
    </thead>
    <tr>
      <td>
        1
      </td>
      <td>
        id
      </td>
      <td>
        {{rsyslogs.id}}
      </td>
    </tr>

    <tr>
      <td>
        2
      </td>
      <td>
        CustomerID
      </td>
      <td>
        {{rsyslogs.CustomerID}}
      </td>
    </tr>
    <tr>
      <td>
        3
      </td>
      <td>
        ReceivedAt
      </td>
      <td>
        {{rsyslogs.ReceivedAt}}
      </td>
    </tr>


    <tr>
      <td>
        4
      </td>
      <td>
        DeviceReportedTime
      </td>
      <td>
        {{rsyslogs.DeviceReportedTime}}
      </td>
    </tr>




    <tr>
      <td>
        5
      </td>
      <td>
        Facility
      </td>
      <td>
        {{rsyslogs.Facility}}
      </td>
    </tr>




    <tr>
      <td>
        6
      </td>
      <td>
        Priority
      </td>
      <td>
        {{rsyslogs.Priority}}
      </td>
    </tr>





    <tr>
      <td>
        7
      </td>
      <td>
        FromHost
      </td>
      <td>
        {{rsyslogs.FromHost}}
      </td>
    </tr>





    <tr>
      <td>
        8
      </td>
      <td>
        Message
      </td>
      <td>
        {{rsyslogs.Message}}
      </td>
    </tr>




    <tr>
      <td>
        9
      </td>
      <td>
        NTSeverity
      </td>
      <td>
        {{rsyslogs.NTSeverity}}
      </td>
    </tr>



    <tr>
      <td>
        10
      </td>
      <td>
        Importance
      </td>
      <td>
        {{rsyslogs.Importance}}
      </td>
    </tr>



    <tr>
      <td>
        11
      </td>
      <td>
        DeviceReportedTime
      </td>
      <td>
        {{rsyslogs.DeviceReportedTime}}
      </td>
    </tr>


    <tr>
      <td>
        12
      </td>
      <td>
        EventSource
      </td>
      <td>
        {{rsyslogs.EventSource}}
      </td>
    </tr>



    <tr>
      <td>
        13
      </td>
      <td>
        EventUser
      </td>
      <td>
        {{rsyslogs.EventUser}}
      </td>
    </tr>




    <tr>
      <td>
        14
      </td>
      <td>
        EventCategory
      </td>
      <td>
        {{rsyslogs.EventCategory}}
      </td>
    </tr>


    <tr>
      <td>
        15
      </td>
      <td>
        DeviceReportedTime
      </td>
      <td>
        {{rsyslogs.DeviceReportedTime}}
      </td>
    </tr>



    <tr>
      <td>
        16
      </td>
      <td>
        EventID
      </td>
      <td>
        {{rsyslogs.EventID}}
      </td>
    </tr>




    <tr>
      <td>
        17
      </td>
      <td>
        EventBinaryData
      </td>
      <td>
        {{rsyslogs.EventBinaryData}}
      </td>
    </tr>




    <tr>
      <td>
        18
      </td>
      <td>
        MaxAvailable
      </td>
      <td>
        {{rsyslogs.MaxAvailable}}
      </td>
    </tr>




    <tr>
      <td>
        19
      </td>
      <td>
        CurrUsage
      </td>
      <td>
        {{rsyslogs.CurrUsage}}
      </td>
    </tr>

      <tr>
      <td>
        20
      </td>
      <td>
        MinUsage
      </td>
      <td>
        {{rsyslogs.MinUsage}}
      </td>
    </tr>

      <tr>
      <td>
        21
      </td>
      <td>
        InfoUnitID
      </td>
      <td>
        {{rsyslogs.InfoUnitID}}
      </td>
    </tr>

      <tr>
      <td>
        22
      </td>
      <td>
        SysLogTag
      </td>
      <td>
        {{rsyslogs.SysLogTag}}
      </td>
    </tr>



    <tbody>
    </tbody>
</table>
{%endblock%}
</body>
</html>

mysite/mysite/templates/monitor/index.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<div class="container">
  <h2>test</h2>
  <p>test</p>
  <div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>번호</th>
        <th>ReceivedAt</th>
        <th>FromHost</th>
        <th>Message</th>
        <th>수정</th>
        <th>삭제</th>
      </tr>
    </thead>
    <tbody>
{% for data in rsyslogs %}
      <tr>
        <td><a href="{% url 'monitor:detail' data.id %}">{{data.id}}</a></td>
        <td>{{data.ReceivedAt}}</td>
        <td>{{data.FromHost}}</td>
        <td>{{data.Message}}</td>
        <td><a href="{% url 'monitor:detail' data.id %}">{{data.id}}</a></td>
        <td><a href="{% url 'monitor:detail' data.id %}">{{data.id}}</a></td>
      </tr>
{% endfor %}
    </tbody>
  </table>
  </div>
</div>
{%endblock%}
</body>
</html>